"""Prompt registry for elicitation, agile analysis, prototyping, and testing."""
from .elicitation_prompts import (
    PROMPT_STAGE_1_STAKEHOLDERS,
    PROMPT_STAGE_2_GOALS,
    PROMPT_STAGE_3_SELECTION,
    PROMPT_STAGE_4_ELICITATION,
    PROMPT_STAGE_5_REQUIREMENTS,
)
from .agile_prompts import (
    PROMPT_STAGE_6_USER_STORIES,
    PROMPT_STAGE_7_INVEST,
    PROMPT_STAGE_8_SPRINTS,
    PROMPT_STAGE_9_TECH_STACK,
    PROMPT_STAGE_9_PROTOTYPE,
    PROMPT_STAGE_10_TEST_CASES,
    PROMPT_STAGE_11_AUTO_HEAL,
)

__all__ = [
    "PROMPT_STAGE_1_STAKEHOLDERS",
    "PROMPT_STAGE_2_GOALS",
    "PROMPT_STAGE_3_SELECTION",
    "PROMPT_STAGE_4_ELICITATION",
    "PROMPT_STAGE_5_REQUIREMENTS",
    "PROMPT_STAGE_6_USER_STORIES",
    "PROMPT_STAGE_7_INVEST",
    "PROMPT_STAGE_8_SPRINTS",
    "PROMPT_STAGE_9_TECH_STACK",
    "PROMPT_STAGE_9_PROTOTYPE",
    "PROMPT_STAGE_10_TEST_CASES",
    "PROMPT_STAGE_11_AUTO_HEAL",
]
